// <auto-generated />
namespace iziWSH_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BuscarrrCep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BuscarrrCep));
        
        string IMigrationMetadata.Id
        {
            get { return "201811180513169_BuscarrrCep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
